# Generated by Django 3.1.6 on 2021-02-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('albumName', models.CharField(max_length=70)),
                ('artist', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('releaseDate', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerId', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('courier', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('productId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingBasketItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.IntegerField()),
                ('productId', models.IntegerField()),
            ],
        ),
    ]
