# Generated by Django 3.1.5 on 2021-03-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc_pirate_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='albumArt',
            field=models.FileField(blank=True, upload_to='album_art'),
        ),
    ]
