# Generated by Django 3.1.5 on 2021-02-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc_pirate_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merch',
            options={'verbose_name_plural': 'Merchandise'},
        ),
    ]
