# Generated by Django 3.1.6 on 2021-03-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disc_pirate_store', '0002_album_albumart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shoppingbasket',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='shoppingbasketitems',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='shoppingbasketitems',
            name='productId',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disc_pirate_store.album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingbasket',
            name='userId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='disc_pirate_store.causer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingbasketitems',
            name='basket_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disc_pirate_store.shoppingbasket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingbasketitems',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='disc_pirate_store.album'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingbasketitems',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='orderId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shoppingbasketitems',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
