# Generated by Django 3.1.5 on 2021-02-18 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc_pirate_store', '0002_auto_20210218_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='format',
        ),
    ]
