# Generated by Django 3.1.5 on 2021-03-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc_pirate_store', '0003_auto_20210310_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerId',
            new_name='userId',
        ),
    ]
