# Generated by Django 3.1.5 on 2021-03-13 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc_pirate_store', '0005_auto_20210313_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingbasketitems',
            old_name='product',
            new_name='productId',
        ),
    ]
