# Generated by Django 3.1.5 on 2021-03-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc_pirate_store', '0006_auto_20210313_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingbasketitems',
            old_name='productId',
            new_name='albumId',
        ),
    ]
