# Generated by Django 3.1.5 on 2021-03-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disc_pirate_store', '0008_auto_20210313_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='album',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='orderId',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='productId',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='disc_pirate_store.causer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='disc_pirate_store.order'),
            preserve_default=False,
        ),
    ]
