# Generated by Django 3.1.5 on 2021-03-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc_pirate_store', '0009_auto_20210314_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cardNumber',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
