# Generated by Django 3.1.5 on 2021-03-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc_pirate_store', '0011_auto_20210314_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cardNumber',
        ),
        migrations.AddField(
            model_name='order',
            name='contactNumber',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
